--!strict

local RemoteNames = {
	GetSession = "GetSession",
	CompleteOnboarding = "CompleteOnboarding",
	SetDisplayName = "SetDisplayName",
	PlayGame = "PlayGame",
	ToggleFavorite = "ToggleFavorite",
	ToggleLike = "ToggleLike",
	EquipItem = "EquipItem",
	UnequipItem = "UnequipItem",
	PurchaseItem = "PurchaseItem",
	SaveAvatar = "SaveAvatar",
	ResetAvatar = "ResetAvatar",
	SaveSettings = "SaveSettings",
	GetFriends = "GetFriends",
	FriendRequest = "FriendRequest",
	FriendRespond = "FriendRespond",
	RemoveFriend = "RemoveFriend",
	SearchPlayers = "SearchPlayers",
	MarkNotificationsRead = "MarkNotificationsRead",
	ClearNotifications = "ClearNotifications",
	AdminCommand = "AdminCommand",
	GetPublicProfile = "GetPublicProfile",
	MatchAction = "MatchAction",
	LeaveMatch = "LeaveMatch",
	PlayAgain = "PlayAgain",
	ClaimDaily = "ClaimDaily",
	GetQuests = "GetQuests",
	GetLeaderboard = "GetLeaderboard",
	GetDaily = "GetDaily",
	PartyInvite = "PartyInvite",
	PartyRespond = "PartyRespond",
	PartyLeave = "PartyLeave",
	GetParty = "GetParty",

	DataUpdate = "DataUpdate",
	Notification = "Notification",
	Announcement = "Announcement",
	CurrencyDelta = "CurrencyDelta",
	SoftError = "SoftError",
}

RemoteNames.Functions = {
	"GetSession",
	"CompleteOnboarding",
	"SetDisplayName",
	"PlayGame",
	"ToggleFavorite",
	"ToggleLike",
	"EquipItem",
	"UnequipItem",
	"PurchaseItem",
	"SaveAvatar",
	"ResetAvatar",
	"SaveSettings",
	"GetFriends",
	"FriendRequest",
	"FriendRespond",
	"RemoveFriend",
	"SearchPlayers",
	"MarkNotificationsRead",
	"ClearNotifications",
	"AdminCommand",
	"GetPublicProfile",
	"MatchAction",
	"LeaveMatch",
	"PlayAgain",
	"ClaimDaily",
	"GetQuests",
	"GetLeaderboard",
	"GetDaily",
	"PartyInvite",
	"PartyRespond",
	"PartyLeave",
	"GetParty",
}

RemoteNames.Events = {
	"DataUpdate",
	"Notification",
	"Announcement",
	"CurrencyDelta",
	"SoftError",
	"MatchState",
	"MatchEvent",
}

return table.freeze(RemoteNames)
